-- 1. Drop table if exists
DECLARE
  table_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO table_exists FROM user_tables WHERE table_name = 'COUNTRIES';
  
  IF table_exists > 0 THEN
    EXECUTE IMMEDIATE 'DROP TABLE Countries';
  END IF;
END;
/

-- 2. Create table
CREATE TABLE Countries (
  ID NUMBER,
  Country VARCHAR2(255),
  Code VARCHAR2(10),
  ICAO VARCHAR2(10)
);

-- 3. Insert data 
BEGIN
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (1, 'ADEN', 'YEM', 'OY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (2, 'AFGHANISTAN', 'AFG', 'OA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (3, 'ALBANIA', 'ALB', 'LA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (4, 'ALGERIA', 'DZA', 'DA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (5, 'AMERICAN SAMOA', 'ASM', 'NS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (6, 'ANDORRA', 'AND', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (7, 'ANGOLA', 'AGO', 'FN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (8, 'ANGUILLA', 'AIA', 'TQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (9, 'ANTARCTICA', 'ATA', 'NZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (10, 'ANTIGUA & BARBUDA', 'ATG', 'TA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (11, 'ANTIGUA AND BARBUDA', 'ATG', 'TA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (12, 'ARGENTINA', 'ARG', 'SA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (13, 'ARMENIA', 'ARM', 'UD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (14, 'ARUBA', 'ABW', 'TN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (15, 'AUSTRALIA', 'AUS', 'Y');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (16, 'AUSTRIA', 'AUT', 'LO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (17, 'AZERBAIJAN', 'AZE', 'UB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (18, 'AZORES', 'PRT', 'LP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (19, 'BAHAMAS', 'BHS', 'MY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (20, 'BAHRAIN', 'BHR', 'OB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (21, 'BANGLADESH', 'BGD', 'VG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (22, 'BARBADOS', 'BRB', 'TB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (23, 'BELARUS', 'BLR', 'UM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (24, 'BELGIUM', 'BEL', 'EB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (25, 'BELIZE', 'BLZ', 'MZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (26, 'BENIN', 'BEN', 'DB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (27, 'BERMUDA', 'BMU', 'TX');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (28, 'BHUTAN', 'BTN', 'VQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (29, 'BOLIVIA', 'BOL', 'SL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (30, 'BOSNIA & HERZEGOVI', 'BIH', 'LQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (31, 'BOSNIA & HERZEGOWINA', 'BIH', 'LQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (32, 'BOSNIA AND HERZEGOWINA', 'BIH', 'LQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (33, 'BOTSWANA', 'BWA', 'FB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (34, 'BOUVET ISLAND', 'BVT', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (35, 'BRAZIL', 'BRA', 'SI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (36, 'BRITISH HONDURAS', 'BLZ', 'MH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (37, 'BRITISH INDIAN OCEAN TERRITORY', 'IOT', 'FJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (38, 'BRITISH INDIAN OCN TERRITORY', 'IOT', 'FJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (39, 'BRITISH VIRGIN IS', 'VGB', 'TU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (40, 'BRITISH WST INDIES', 'AIA', 'TQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (41, 'BRUNEI', 'BRN', 'WB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (42, 'BRUNEI DARUSSALAM', 'BRN', 'WB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (43, 'BULGARIA', 'BGR', 'LB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (44, 'BURKINA', 'BFA', 'DF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (45, 'BURKINA FASO', 'BFA', 'DF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (46, 'BURMA', 'MMR', 'VY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (47, 'BURUNDI', 'BDI', 'HB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (48, 'CAMBODIA', 'KHM', 'VD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (49, 'CAMEROON', 'CMR', 'FK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (50, 'CANADA', 'CAN', 'C');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (51, 'CANAL ZONE', 'UNK', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (52, 'CANARY ISLANDS', 'ESP', 'GC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (53, 'CAPE VERDE', 'CPV', 'GV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (54, 'CAYMAN ISLANDS', 'CYM', 'MW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (55, 'CENTRAL AFRICAN REPUBLIC', 'CAF', 'FE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (56, 'CENTRAL AFRICAN RP', 'CAF', 'FE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (57, 'CEYLON', 'LKA', 'VC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (58, 'CHAD', 'TCD', 'FT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (59, 'CHANNEL ISLES', 'GBR', 'EG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (60, 'CHILE', 'CHL', 'SC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (61, 'CHINA', 'CHN', 'Z');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (62, 'CHRISTMAS ISLAND', 'CXR', 'YP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (63, 'COCOS (KEELING) ISLANDS', 'CCK', 'YP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (64, 'COLOMBIA', 'COL', 'SK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (65, 'COMOROS', 'COM', 'FM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (66, 'CONGO', 'COD', 'FZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (67, 'CONGO, Democratic Republic of (was Zaire)', 'COD', 'FZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (68, 'CONGO, People''s Republic of', 'COG', 'FC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (69, 'COOK ISLANDS', 'COK', 'NC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (70, 'COSTA RICA', 'CRI', 'MR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (71, 'COTE D''IVOIRE', 'CIV', 'DI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (72, 'CROATIA', 'HRV', 'LD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (73, 'CROATIA (local name: Hrvatska)', 'HRV', 'LD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (74, 'CUBA', 'CUB', 'MU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (75, 'CYPRUS', 'CYP', 'LC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (76, 'CZECH REPUBLIC', 'CZE', 'LK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (77, 'CZECHOSLOVAKIA', 'CZE', 'LZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (78, 'DEM REP CONGO', 'COD', 'FZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (79, 'DENMARK', 'DNK', 'EK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (80, 'DJIBOUTI', 'DJI', 'HF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (81, 'DOMINICA', 'DMA', 'TD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (82, 'DOMINICAN REPUBLIC', 'DOM', 'MD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (83, 'EAST GERMANY', 'DEU', 'ED');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (84, 'EAST TIMOR', 'TLS', 'WP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (85, 'ECUADOR', 'ECU', 'SE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (86, 'EGYPT', 'EGY', 'HE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (87, 'EL SALVADOR', 'SLV', 'MS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (88, 'EQUATORIAL GUINEA', 'GNQ', 'GU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (89, 'ERITREA', 'ERI', 'HH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (90, 'ESTONIA', 'EST', 'EE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (91, 'ETHIOPIA', 'ETH', 'HA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (92, 'FALKLAND ISLANDS', 'FLK', 'SF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (93, 'FALKLAND ISLANDS (MALVINAS)', 'FLK', 'SF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (94, 'FAROE ISLANDS', 'FRO', 'EK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (95, 'FIJI', 'FJI', 'NF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (96, 'FINLAND', 'FIN', 'EF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (97, 'FRANCE', 'FRA', 'LF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (98, 'FRANCE, METROPOLITAN', 'FXX', 'LF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (99, 'FRENCH AFARS-ISSAS', 'DJI', 'HD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (100, 'FRENCH GUIANA', 'GUF', 'SO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (101, 'FRENCH POLYNESIA', 'PYF', 'NT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (102, 'FRENCH SOUTHERN TERRITORIES', 'ATF', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (103, 'FRENCH WEST INDIES', 'GLP', 'TF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (104, 'GABON', 'GAB', 'FO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (105, 'GAMBIA', 'GMB', 'GB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (106, 'GEORGIA', 'GEO', 'UG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (107, 'GERMANY', 'DEU', 'ED');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (108, 'GERMANY BERLIN', 'DEU', 'ED');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (109, 'GHANA', 'GHA', 'DG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (110, 'GIBRALTAR', 'GIB', 'LX');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (111, 'GREECE', 'GRC', 'LG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (112, 'GREENLAND', 'GRL', 'BG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (113, 'GRENADA', 'GRD', 'TG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (114, 'GUADELOUPE', 'GLP', 'TF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (115, 'GUAM', 'GUM', 'PG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (116, 'GUATEMALA', 'GTM', 'MG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (117, 'GUINEA', 'GIN', 'GU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (118, 'GUINEA-BISSAU', 'GNB', 'GG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (119, 'GUYANA', 'GUY', 'SY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (120, 'HAITI', 'HTI', 'MT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (121, 'HEARD AND MC DONALD ISLANDS', 'HMD', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (122, 'HONDURAS', 'HND', 'MH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (123, 'HONG KONG', 'HKG', 'VH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (124, 'HUNGARY', 'HUN', 'LH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (125, 'ICELAND', 'ISL', 'BI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (126, 'INDIA', 'IND', 'VI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (127, 'INDONESIA', 'IDN', 'WR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (128, 'IRAN', 'IRN', 'OI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (129, 'IRAN (ISLAMIC REPUBLIC OF)', 'IRN', 'OI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (130, 'IRAQ', 'IRQ', 'OR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (131, 'IRELAND', 'IRL', 'EI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (132, 'ISRAEL', 'ISR', 'LL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (133, 'ITALY', 'ITA', 'LI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (134, 'JAMAICA', 'JAM', 'MK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (135, 'JAPAN', 'JPN', 'RJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (136, 'JERSEY', 'GBR', 'EG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (137, 'JORDAN', 'JOR', 'OJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (138, 'KAZAKHSTAN', 'KAZ', 'UA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (139, 'KENYA', 'KEN', 'HK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (140, 'KIRIBATI', 'KIR', 'NG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (141, 'KOREA NORTH', 'PRK', 'ZK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (142, 'KOREA REPUBLIC OF', 'KOR', 'RK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (143, 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 'PRK', 'ZK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (144, 'KOREA, REPUBLIC OF', 'KOR', 'RK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (145, 'KUWAIT', 'KWT', 'OK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (146, 'KYRGYZSTAN', 'KGZ', 'UA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (147, 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 'LAO', 'VL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (148, 'LAOS', 'LAO', 'VL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (149, 'LATVIA', 'LVA', 'EV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (150, 'LEBANON', 'LBN', 'OL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (151, 'LESOTHO', 'LSO', 'FX');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (152, 'LIBERIA', 'LBR', 'GL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (153, 'LIBYA', 'LBY', 'HL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (154, 'LIBYAN ARAB JAMAHIRIYA', 'LBY', 'HL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (155, 'LIECHTENSTEIN', 'LIE', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (156, 'LITHUANIA', 'LTU', 'EY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (157, 'LUXEMBOURG', 'LUX', 'EL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (158, 'MACAU', 'MAC', 'VM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (159, 'MACEDONIA', 'MKD', 'LW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (160, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MKD', 'LW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (161, 'MADAGASCAR', 'MDG', 'FM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (162, 'MALAWI', 'MWI', 'FW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (163, 'MALAYSIA', 'MYS', 'WB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (164, 'MALAYSIA (ASIA)', 'MYS', 'WB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (165, 'MALDIVES', 'MDV', 'VR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (166, 'MALI', 'MLI', 'GA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (167, 'MALTA', 'MLT', 'LM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (168, 'MARSHALL ISLANDS', 'MHL', 'PK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (169, 'MARTINIQUE', 'MTQ', 'TF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (170, 'MAURITANIA', 'MRT', 'GQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (171, 'MAURITIUS', 'MUS', 'FI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (172, 'MAYOTTE', 'MYT', 'FM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (173, 'MEXICO', 'MEX', 'MM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (174, 'MICRONESIA, FEDERATED STATES OF', 'FSM', 'PT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (175, 'MOLDOVA, REPUBLIC OF', 'MDA', 'LU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (176, 'MONACO', 'MCO', 'LN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (177, 'MONGOLIA', 'MNG', 'ZM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (178, 'MONTENEGRO', 'YUG', 'LY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (179, 'MONTSERRAT', 'MSR', 'TR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (180, 'MOROCCO', 'MAR', 'GM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (181, 'MOZAMBIQUE', 'MOZ', 'FQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (182, 'MUSCAT AND OMAN', 'OMN', 'OO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (183, 'MYANMAR', 'MMR', 'VY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (184, 'NAMIBIA', 'NAM', 'FY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (185, 'NAURU', 'NRU', 'AN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (186, 'NAVASSA ISLAND', 'UNK', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (187, 'NEPAL', 'NPL', 'VN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (188, 'NETHERLANDS', 'NLD', 'EH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (189, 'NETHERLANDS ANTILLES', 'ANT', 'EH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (190, 'NEW CALEDONIA', 'NCL', 'NW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (191, 'NEW GUINEA', 'PNG', 'GU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (192, 'NEW ZEALAND', 'NZL', 'NZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (193, 'NICARAGUA', 'NIC', 'MN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (194, 'NIGER', 'NER', 'DR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (195, 'NIGERIA', 'NGA', 'DN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (196, 'NIUE', 'NIU', 'NI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (197, 'NORFOLK ISLAND', 'NFK', 'YS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (198, 'NORTHERN MARIANA ISLANDS', 'MNP', 'PG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (199, 'NORWAY', 'NOR', 'EN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (200, 'OMAN', 'OMN', 'OO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (201, 'PAKISTAN', 'PAK', 'OP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (202, 'PALAU', 'PLW', 'PT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (203, 'PALESTINE', 'PSE', 'LV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (204, 'PALESTINIAN TERRITORY, Occupied', 'PSE', 'LV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (205, 'PANAMA', 'PAN', 'MP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (206, 'PAPUA NEW GUINEA', 'PNG', 'AY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (207, 'PARAGUAY', 'PRY', 'SG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (208, 'PERU', 'PER', 'SP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (209, 'PHILIPPINES', 'PHL', 'RP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (210, 'PITCAIRN', 'PCN', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (211, 'POLAND', 'POL', 'EP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (212, 'PORTUGAL', 'PRT', 'LP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (213, 'PUERTO RICO', 'PRI', 'TJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (214, 'QATAR', 'QAT', 'OT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (215, 'REUNION', 'REU', 'FM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (216, 'ROMANIA', 'ROU', 'LR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (217, 'RUSSIA', 'RUS', 'U');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (218, 'RUSSIAN FEDERATION', 'RUS', 'U');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (219, 'RWANDA', 'RWA', 'HR');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (220, 'SAINT KITTS AND NEVIS', 'KNA', 'TK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (221, 'SAINT LUCIA', 'LCA', 'TL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (222, 'SAINT VINCENT AND THE GRENADINES', 'VCT', 'TV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (223, 'SAIPAN', 'MNP', 'PG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (224, 'SAMOA', 'WSM', 'NS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (225, 'SAN MARINO', 'SMR', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (226, 'SAO TOME AND PRINCIPE', 'STP', 'FP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (227, 'SAO TOME PRINCIPE', 'STP', 'FP');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (228, 'SAUDI ARABIA', 'SAU', 'OE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (229, 'SENEGAL', 'SEN', 'GO');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (230, 'SERBIA', 'YUG', 'LY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (231, 'SEYCHELLES', 'SYC', 'FS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (232, 'SIERRA LEONE', 'SLE', 'GF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (233, 'SINGAPORE', 'SGP', 'WS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (234, 'SLOVAKIA', 'SVK', 'LZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (235, 'SLOVAKIA (Slovak Republic)', 'SVK', 'LZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (236, 'SLOVENIA', 'SVN', 'LJ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (237, 'SOLOMON ISLANDS', 'SLB', 'AG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (238, 'SOMALIA', 'SOM', 'HC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (239, 'SOUTH AFRICA', 'ZAF', 'FA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (240, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'SGS', 'UG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (241, 'SOUTH RHODESIA', 'ZWE', 'FV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (242, 'SOUTH-WEST AFRICA', 'ZAF', 'FA');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (243, 'SOVIET UNION', 'RUS', 'U');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (244, 'SPAIN', 'ESP', 'LE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (245, 'SRI LANKA', 'LKA', 'VC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (246, 'ST CHRIS AND NEVIS', 'KNA', 'TK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (247, 'ST HELENA', 'SHN', 'FH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (248, 'ST KITTS AND NEVIS', 'KNA', 'TK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (249, 'ST LUCIA', 'LCA', 'TL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (250, 'ST VINCENT & GRENA', 'VCT', 'TV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (251, 'ST. HELENA', 'SHN', 'FH');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (252, 'ST. PIERRE AND MIQUELON', 'SPM', 'LF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (253, 'STATELESS', 'UNK', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (254, 'SUDAN', 'SDN', 'HS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (255, 'SURINAME', 'SUR', 'SM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (256, 'SVALBARD AND JAN MAYEN ISLANDS', 'SJM', 'EN');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (257, 'SWAZILAND', 'SWZ', 'FD');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (258, 'SWEDEN', 'SWE', 'ES');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (259, 'SWITZERLAND', 'CHE', 'LS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (260, 'SYRIA', 'SYR', 'OS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (261, 'SYRIAN ARAB REPUBLIC', 'SYR', 'OS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (262, 'TAIWAN', 'TWN', 'RC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (263, 'TAIWAN ROC', 'TWN', 'RC');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (264, 'TAJIKISTAN', 'TJK', 'UT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (265, 'TANZANIA', 'TZA', 'HT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (266, 'TANZANIA, UNITED REPUBLIC OF', 'TZA', 'HT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (267, 'THAILAND', 'THA', 'VT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (268, 'TOGO', 'TGO', 'DX');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (269, 'TOKELAU', 'TKL', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (270, 'TONGA', 'TON', 'NF');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (271, 'TRINIDAD & TOBAGO', 'TTO', 'TT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (272, 'TRINIDAD AND TOBAGO', 'TTO', 'TT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (273, 'TRUST TERR PAC ISL', 'MHL', 'PK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (274, 'TUNISIA', 'TUN', 'DT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (275, 'TURKEY', 'TUR', 'LT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (276, 'TURKMENISTAN', 'TKM', 'UT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (277, 'TURKS & CAICOS ISL', 'TCA', 'MB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (278, 'TURKS & CAICOS ISLANDS', 'TCA', 'MB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (279, 'TURKS AND CAICOS ISLANDS', 'TCA', 'MB');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (280, 'TUVALU', 'TUV', 'NG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (281, 'UAR', 'EGY', 'HE');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (282, 'UGANDA', 'UGA', 'HU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (283, 'UKRAINE', 'UKR', 'UK');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (284, 'UNITED ARAB EMIRATES', 'ARE', 'OM');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (285, 'UNITED KINGDOM', 'GBR', 'EG');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (286, 'UNITED STATES', 'USA', 'K');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (287, 'UNITED STATES MINOR OUTLYING ISLANDS', 'UMI', 'K');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (288, 'UNKNOWN', 'UNK', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (289, 'URUGUAY', 'URY', 'SU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (290, 'UZBEKISTAN', 'UZB', 'UT');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (291, 'VANUATU', 'VUT', 'NV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (292, 'VATICAN CITY STATE (HOLY SEE)', 'VAT', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (293, 'VENEZUELA', 'VEN', 'SV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (294, 'VIET NAM', 'VNM', 'VV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (295, 'VIETNAM', 'VNM', 'VV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (296, 'VIRGIN ISLANDS (BRITISH)', 'VGB', 'TU');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (297, 'VIRGIN ISLANDS (U.S.)', 'VIR', 'TI');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (298, 'WAKE ISLAND', 'UMI', 'PW');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (299, 'WALLIS & FUTUNA ISLANDS', 'WLF', 'NL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (300, 'WALLIS AND FUTUNA ISLANDS', 'WLF', 'NL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (301, 'WEST GERMANY', 'DEU', 'ED');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (302, 'WEST INDIES', 'AIA', 'TQ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (303, 'WESTERN SAHARA', 'ESH', 'GS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (304, 'WESTERN SAMOA', 'WSM', 'NS');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (305, 'YEMEN', 'YEM', 'OY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (306, 'YEMEN (ADEN)', 'YEM', 'OY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (307, 'YEMEN (SANAA)', 'YEM', 'OY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (308, 'YUGOSLAVIA', 'YUG', 'LY');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (309, 'ZAIRE', 'COD', 'FZ');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (310, 'ZAMBIA', 'ZMB', 'FL');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (311, 'ZIMBABWE', 'ZWE', 'FV');
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (312, 'ISLE OF MAN', 'IMN', NULL);
  INSERT INTO Countries (ID, Country, Code, ICAO) VALUES (315, 'Guernsey', 'GG', 'GC');
  
  COMMIT;
END;