CREATE TABLE EMAIL_VERIFICATION_TOKENS (
    TOKEN_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    TOKEN_HASH VARCHAR2(200) NOT NULL,
    EXPIRES_AT DATE NOT NULL,
    USED NUMBER(1) DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_EMAIL_VERIFICATION_TOKENS PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_EMAIL_VERIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS (USER_ID),
    CONSTRAINT CK_EMAIL_VERIFICATION_USED CHECK (USED IN (0, 1))
);

CREATE INDEX IDX_EMAIL_VERIFICATION_TOKEN_HASH ON EMAIL_VERIFICATION_TOKENS (TOKEN_HASH);

CREATE INDEX IDX_EMAIL_VERIFICATION_USER_ID ON EMAIL_VERIFICATION_TOKENS (USER_ID);

CREATE INDEX IDX_EMAIL_VERIFICATION_EXPIRES ON EMAIL_VERIFICATION_TOKENS (EXPIRES_AT);