CREATE TABLE PASSWORD_RESET_TOKENS (
    TOKEN_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    TOKEN_HASH VARCHAR2(200) NOT NULL,
    EXPIRES_AT DATE NOT NULL,
    USED NUMBER(1) DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PASSWORD_RESET_TOKENS PRIMARY KEY (TOKEN_ID),
    CONSTRAINT FK_PASSWORD_RESET_USER FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS (USER_ID),
    CONSTRAINT CK_PASSWORD_RESET_USED CHECK (USED IN (0, 1))
);

-- Index for faster lookups
CREATE INDEX IDX_PASSWORD_RESET_TOKEN_HASH ON PASSWORD_RESET_TOKENS (TOKEN_HASH);

CREATE INDEX IDX_PASSWORD_RESET_USER_ID ON PASSWORD_RESET_TOKENS (USER_ID);

CREATE INDEX IDX_PASSWORD_RESET_EXPIRES ON PASSWORD_RESET_TOKENS (EXPIRES_AT);