CREATE TABLE PROFILE_ROLES (
    ROLE_ID VARCHAR2(36) NOT NULL,
    USER_ID VARCHAR2(36) NOT NULL,
    ROLE_NAME VARCHAR2(100) NOT NULL,
    ASSIGNED_BY VARCHAR2(36),
    ASSIGNED_DATE DATE DEFAULT SYSDATE,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (ROLE_ID),
    CONSTRAINT FK_PROFILE_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES ACCOUNTS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROFILE_ROLES_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY) REFERENCES ACCOUNTS (USER_ID)
);

CREATE INDEX IDX_PROFILE_ROLES_USER_ID ON PROFILE_ROLES (USER_ID);

CREATE INDEX IDX_PROFILE_ROLES_ROLE_NAME ON PROFILE_ROLES (ROLE_NAME);

CREATE INDEX IDX_PROFILE_ROLES_ACTIVE ON PROFILE_ROLES (IS_ACTIVE);