DROP TABLE AAPUSER.WAIVER_DATA CASCADE CONSTRAINTS;

CREATE TABLE AAPUSER.WAIVER_DATA
(
  WAIVER_ID               VARCHAR2(500 BYTE),
  USER_ID                 VARCHAR2(20 BYTE),
  APPLICATION_DATE        DATE,
  START_DATE              DATE,
  END_DATE                DATE,
  WAIVER_TYPE             NVARCHAR2(50),
  WAIVER_SUBTYPE          NVARCHAR2(15),
  REQ_TITLE               NVARCHAR2(10),
  REQ_FIRST_NAME          NVARCHAR2(50),
  REQ_MIDDLE_NAME         NVARCHAR2(50),
  REQ_LAST_NAME           NVARCHAR2(50),
  REQ_ORGANIZATION        VARCHAR2(250 BYTE),
  REQ_STREET_ADDR         NVARCHAR2(50),
  REQ_CITY                NVARCHAR2(50),
  REQ_STATE               NVARCHAR2(50),
  REQ_ZIP_CODE            VARCHAR2(20 BYTE),
  REQ_COUNTRY             NVARCHAR2(50),
  REQ_PRIMARY_PHONE       VARCHAR2(20 BYTE),
  REQ_24H_PHONE           VARCHAR2(20 BYTE),
  REQ_PRIMARY_EMAIL       NVARCHAR2(250),
  OP_TITLE                NVARCHAR2(10),
  OP_FIRST_NAME           NVARCHAR2(50),
  OP_MIDDLE_NAME          NVARCHAR2(50),
  OP_LAST_NAME            NVARCHAR2(50),
  OP_ORGANIZATION         VARCHAR2(250 BYTE),
  OP_STREET_ADDR          NVARCHAR2(50),
  OP_CITY                 NVARCHAR2(50),
  OP_STATE                NVARCHAR2(50),
  OP_ZIP_CODE             VARCHAR2(20 BYTE),
  OP_COUNTRY              NVARCHAR2(50),
  OP_PRIMARY_PHONE        VARCHAR2(20 BYTE),
  OP_24H_PHONE            VARCHAR2(20 BYTE),
  OP_PRIMARY_EMAIL        NVARCHAR2(250),
  OWN_TITLE               NVARCHAR2(10),
  OWN_FIRST_NAME          NVARCHAR2(50),
  OWN_MIDDLE_NAME         NVARCHAR2(50),
  OWN_LAST_NAME           NVARCHAR2(50),
  OWN_ORGANIZATION        VARCHAR2(250 BYTE),
  OWN_STREET_ADDR         NVARCHAR2(50),
  OWN_CITY                NVARCHAR2(50),
  OWN_STATE               NVARCHAR2(50),
  OWN_ZIP_CODE            VARCHAR2(20 BYTE),
  OWN_COUNTRY             NVARCHAR2(50),
  OWN_PRIMARY_PHONE       VARCHAR2(20 BYTE),
  OWN_24H_PHONE           VARCHAR2(20 BYTE),
  OWN_PRIMARY_EMAIL       NVARCHAR2(250),
  PURPOSE_COMMENTS        NVARCHAR2(2000),
  DASSP_TYPE              NVARCHAR2(50),
  DASSP_COMPANY_NAME      NVARCHAR2(100),
  DASSP_OPERATOR_NUM      NVARCHAR2(100),
  DASSP_SEC_COORDINATOR   NVARCHAR2(100),
  DASSP_DEPART_AIRPORT    NVARCHAR2(100),
  DASSP_DEPART_FBO        NVARCHAR2(100),
  ARRIV_DATE              DATE,
  DEPT_DATE_DCA           DATE,
  DASSP_DEST_AIRPORT      NVARCHAR2(100),
  DIS_PARK                NVARCHAR2(100),
  DIS_DEPART_POINT        NVARCHAR2(100),
  DIS_FINAL_DESTINATION   NVARCHAR2(100),
  DOM_APPROVED_DISTANCE   NVARCHAR2(100),
  DOM_DCA_DISTANCE        NVARCHAR2(100),
  DOM_FRZ_DESTINATION     NVARCHAR2(100),
  DOM_FRZ_OVERFLIGHTS     NVARCHAR2(100),
  FAA_DEPART_AIRPORT      NVARCHAR2(100),
  FAA_INT_STOPS           NVARCHAR2(2000),
  FAA_ARRIVE_AIRPORT      NVARCHAR2(100),
  INTL_SUBTYPE            NVARCHAR2(50),
  INTL_FLIGHT_TYPE        NVARCHAR2(50),
  INTL_DEPART_POINT       NVARCHAR2(2000),
  INTL_INT_STOP           NVARCHAR2(2000),
  INTL_DEST_POINT         NVARCHAR2(2000),
  INTL_FINAL_DESTINATION  NVARCHAR2(2000),
  INTL_AMB_ROUTE          NVARCHAR2(2000),
  INTL_AMB_HOSP_NAME      NVARCHAR2(2000),
  INTL_AMB_HOSP_NUM       NVARCHAR2(2000),
  INTL_AMB_HOSP_ADDRESS   NVARCHAR2(2000),
  INTL_AMB_HOSP_POC       NVARCHAR2(2000),
  INTL_CONTACT_NAME       NVARCHAR2(100),
  INTL_CONTACT_STREET     NVARCHAR2(50),
  INTL_CONTACT_CITY       NVARCHAR2(50),
  INTL_CONTACT_STATE      NVARCHAR2(50),
  INTL_CONTACT_ZIP_CODE   VARCHAR2(20 BYTE),
  INTL_CONTACT_COUNTRY    NVARCHAR2(50),
  INTL_CONTACT_PHONE      VARCHAR2(20 BYTE),
  BAL_DCA_DISTANCE        NVARCHAR2(100),
  BAL_FRZ_DESTINATION     NVARCHAR2(100),
  BAL_FRZ_OVERFLIGHTS     NVARCHAR2(100),
  PAA_DEPART_AIRPORT      NVARCHAR2(100),
  PAA_INT_STOPS           NVARCHAR2(2000),
  PAA_ARRIVE_AIRPORT      NVARCHAR2(100),
  SPE_OPERATION_TYPE      NVARCHAR2(100),
  SPE_DEPART_AIRPORT      NVARCHAR2(100),
  SPE_DEPART_DATETIME     DATE,
  SPE_DAPART_GATEWAY      NVARCHAR2(100),
  SPE_DEPART_SLOT         NUMBER(4),
  SPE_ARRIVE_AIRPORT      NVARCHAR2(100),
  SPE_ARRIVE_DATETIME     DATE,
  SPE_ARRIVE_SLOT         NUMBER(4),
  SPE_OVERFLIGHTS         NVARCHAR2(100),
  SPORT_EVENT_NAME        NVARCHAR2(200),
  SPORT_EVENT_VENUE       NVARCHAR2(200),
  SPORT_PREV_VENUE_NAME   NVARCHAR2(200),
  SPORT_CITY              NVARCHAR2(50),
  SPORT_STATE             NVARCHAR2(50),
  SPORT_ALTITUDE          NVARCHAR2(50),
  UAS_APPROVED_DISTANCE   NVARCHAR2(50),
  DEST_STREET             NVARCHAR2(50),
  DEST_CITY               NVARCHAR2(50),
  DEST_STATE              NVARCHAR2(50),
  DEST_ZIP                VARCHAR2(20 BYTE),
  UAS_DCA_DISTANCE        NVARCHAR2(100),
  FLIGHT_ALTITUDE         NVARCHAR2(50),
  UAS_COORDINATES         NVARCHAR2(200),
  SEC_SECURED             NVARCHAR2(2000),
  SEC_MANIFEST            NVARCHAR2(2000),
  SEC_ADD_SECURITY        NVARCHAR2(2000),
  SEC_TITLE               NVARCHAR2(50),
  SEC_NAME                NVARCHAR2(100),
  SEC_DATE                DATE,
  STATUS                  VARCHAR2(255 BYTE),
  PROCESSING_STEP         VARCHAR2(255 BYTE),
  CONFIRMATION            NUMBER(*,1),
  ARCHIVED                NUMBER(1)             DEFAULT 0                     NOT NULL,
  SEC_ACCEPTED            VARCHAR2(2 BYTE),
  DEPT_TIME               NUMBER(5),
  ARRIV_TIME              NUMBER(5),
  DEPT_TIME_DCA           NUMBER(5),
  DEPT_DATE               DATE,
  DAS_COORDINATOR         VARCHAR2(200 BYTE),
  DCARADDIST              VARCHAR2(400 BYTE),
  LAT_LONG                VARCHAR2(500 BYTE)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE AAPUSER.WAIVER_DATA ADD (
  PRIMARY KEY
  (WAIVER_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE
,  UNIQUE (CONFIRMATION)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


--  There is no statement for index AAPUSER.SYS_C008361.
--  The object is created when the parent object is created.
--  There is no statement for index AAPUSER.SYS_C008362.
--  The object is created when the parent object is created.
ALTER TABLE AAPUSER.WAIVER_DATA ADD (
  FOREIGN KEY (USER_ID) 
  REFERENCES AAPUSER.ACCOUNTS (USER_ID)
  ENABLE VALIDATE);
