-- 1. Drop table if exists
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM user_tables WHERE table_name = 'WAIVER_PROCESS';
    IF table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE WAIVER_PROCESS';
    END IF;
END;
/

-- 2. Create table with appropriate columns
CREATE TABLE WAIVER_PROCESS (
    WAIVER_ID VARCHAR2(500) NOT NULL,
    PROCESSING_DATE DATE,
    PROCESSING_SIGNOFF VARCHAR2(255),
    PROCESSING_APPROVED CHAR(1) CHECK (
        PROCESSING_APPROVED IN ('Y', 'N')
    ),
    PROCESSING_COMMENTS CLOB,
    DETERMINED_DATE DATE,
    DETERMINED_SIGNOFF VARCHAR2(255),
    DETERMINED_APPROVED CHAR(1) CHECK (
        DETERMINED_APPROVED IN ('Y', 'N')
    ),
    DETERMINED_REJECTION_REASON CLOB,
    DETERMINED_COMMENTS CLOB,
    DETERMINED_APPROVAL_CODE CLOB,
    DETERMINED_PARAGRAPHS CLOB, -- JSON array of paragraph content
    VETTED_DATE DATE,
    VETTED_SIGNOFF VARCHAR2(255),
    VETTED_APPROVED CHAR(1) CHECK (VETTED_APPROVED IN ('Y', 'N')),
    VETTED_COMMENTS CLOB,
    VETTED_APPROVAL_CODE VARCHAR2(255),
    VETTED_REJECTION_REASON CLOB,
    QA_DATE DATE,
    QA_SIGNOFF VARCHAR2(255),
    QA_APPROVED CHAR(1) CHECK (QA_APPROVED IN ('Y', 'N')),
    QA_COMMENTS CLOB,
    QA_APPROVAL_CODE VARCHAR2(255),
    QA_REJECTION_REASON CLOB,
    CERTIFIED_DATE DATE,
    CERTIFIED_SIGNOFF VARCHAR2(255),
    CERTIFIED_APPROVED CHAR(1) CHECK (
        CERTIFIED_APPROVED IN ('Y', 'N')
    ),
    CERTIFIED_COMMENTS CLOB,
    CERTIFIED_APPROVAL_CODE VARCHAR2(255),
    CERTIFIED_REJECTION_REASON CLOB,
    SENT_EMAIL_BODY CLOB,
    SENT_EMAIL_TO VARCHAR2(500),
    SENT_DATE DATE,
    SENT_SIGNOFF VARCHAR2(255),
    SENT_APPROVED CHAR(1) CHECK (SENT_APPROVED IN ('Y', 'N')),
    SENT_COMMENTS CLOB,
    CREATED_BY VARCHAR2(255) DEFAULT 'system',
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_BY VARCHAR2(255),
    UPDATED_DATE DATE
);

-- 3. Create indexes for performance
CREATE INDEX IDX_WAIVER_PROCESS_WaiverID ON WAIVER_PROCESS (WaiverID);

CREATE INDEX IDX_WAIVER_PROCESS_ProcessingDate ON WAIVER_PROCESS (ProcessingDate);

CREATE INDEX IDX_WAIVER_PROCESS_DeterminedDate ON WAIVER_PROCESS (DeterminedDate);