export const STATES = [
    {
      name: "Alabama",
      abbreviation: "AL",
      capital: "Montgomery",
      admitted: "1819-12-14",
      region: "South",
      population: 5024279,
      largestCity: "Huntsville",
    },
    {
      name: "Alaska",
      abbreviation: "AK",
      capital: "Juneau",
      admitted: "1959-01-03",
      region: "West",
      population: 733391,
      largestCity: "Anchorage",
    },
    {
      name: "Arizona",
      abbreviation: "AZ",
      capital: "Phoenix",
      admitted: "1912-02-14",
      region: "West",
      population: 7151502,
      largestCity: "Phoenix",
    },
    {
      name: "Arkansas",
      abbreviation: "AR",
      capital: "Little Rock",
      admitted: "1836-06-15",
      region: "South",
      population: 3011524,
      largestCity: "Little Rock",
    },
    {
      name: "California",
      abbreviation: "CA",
      capital: "Sacramento",
      admitted: "1850-09-09",
      region: "West",
      population: 39538223,
      largestCity: "Los Angeles",
    },
    {
      name: "Colorado",
      abbreviation: "CO",
      capital: "Denver",
      admitted: "1876-08-01",
      region: "West",
      population: 5773714,
      largestCity: "Denver",
    },
    {
      name: "Connecticut",
      abbreviation: "CT",
      capital: "Hartford",
      admitted: "1788-01-09",
      region: "Northeast",
      population: 3605944,
      largestCity: "Bridgeport",
    },
    {
      name: "Delaware",
      abbreviation: "DE",
      capital: "Dover",
      admitted: "1787-12-07",
      region: "Northeast",
      population: 989948,
      largestCity: "Wilmington",
    },
    {
      name: "Florida",
      abbreviation: "FL",
      capital: "Tallahassee",
      admitted: "1845-03-03",
      region: "South",
      population: 21538187,
      largestCity: "Jacksonville",
    },
    {
      name: "Georgia",
      abbreviation: "GA",
      capital: "Atlanta",
      admitted: "1788-01-02",
      region: "South",
      population: 10711908,
      largestCity: "Atlanta",
    },
    {
      name: "Hawaii",
      abbreviation: "HI",
      capital: "Honolulu",
      admitted: "1959-08-21",
      region: "West",
      population: 1455271,
      largestCity: "Honolulu",
    },
    {
      name: "Idaho",
      abbreviation: "ID",
      capital: "Boise",
      admitted: "1890-07-03",
      region: "West",
      population: 1839106,
      largestCity: "Boise",
    },
    {
      name: "Illinois",
      abbreviation: "IL",
      capital: "Springfield",
      admitted: "1818-12-03",
      region: "Midwest",
      population: 12812508,
      largestCity: "Chicago",
    },
    {
      name: "Indiana",
      abbreviation: "IN",
      capital: "Indianapolis",
      admitted: "1816-12-11",
      region: "Midwest",
      population: 6785528,
      largestCity: "Indianapolis",
    },
    {
      name: "Iowa",
      abbreviation: "IA",
      capital: "Des Moines",
      admitted: "1846-12-28",
      region: "Midwest",
      population: 3190369,
      largestCity: "Des Moines",
    },
    {
      name: "Kansas",
      abbreviation: "KS",
      capital: "Topeka",
      admitted: "1861-01-29",
      region: "Midwest",
      population: 2937880,
      largestCity: "Wichita",
    },
    {
      name: "Kentucky",
      abbreviation: "KY",
      capital: "Frankfort",
      admitted: "1792-06-01",
      region: "South",
      population: 4505836,
      largestCity: "Louisville",
    },
    {
      name: "Louisiana",
      abbreviation: "LA",
      capital: "Baton Rouge",
      admitted: "1812-04-30",
      region: "South",
      population: 4657757,
      largestCity: "New Orleans",
    },
    {
      name: "Maine",
      abbreviation: "ME",
      capital: "Augusta",
      admitted: "1820-03-15",
      region: "Northeast",
      population: 1362359,
      largestCity: "Portland",
    },
    {
      name: "Maryland",
      abbreviation: "MD",
      capital: "Annapolis",
      admitted: "1788-04-28",
      region: "Northeast",
      population: 6177224,
      largestCity: "Baltimore",
    },
    {
      name: "Massachusetts",
      abbreviation: "MA",
      capital: "Boston",
      admitted: "1788-02-06",
      region: "Northeast",
      population: 7029917,
      largestCity: "Boston",
    },
    {
      name: "Michigan",
      abbreviation: "MI",
      capital: "Lansing",
      admitted: "1837-01-26",
      region: "Midwest",
      population: 10077331,
      largestCity: "Detroit",
    },
    {
      name: "Minnesota",
      abbreviation: "MN",
      capital: "St. Paul",
      admitted: "1858-05-11",
      region: "Midwest",
      population: 5706494,
      largestCity: "Minneapolis",
    },
    {
      name: "Mississippi",
      abbreviation: "MS",
      capital: "Jackson",
      admitted: "1817-12-10",
      region: "South",
      population: 2961279,
      largestCity: "Jackson",
    },
    {
      name: "Missouri",
      abbreviation: "MO",
      capital: "Jefferson City",
      admitted: "1821-08-10",
      region: "Midwest",
      population: 6154913,
      largestCity: "Kansas City",
    },
    {
      name: "Montana",
      abbreviation: "MT",
      capital: "Helena",
      admitted: "1889-11-08",
      region: "West",
      population: 1084225,
      largestCity: "Billings",
    },
    {
      name: "Nebraska",
      abbreviation: "NE",
      capital: "Lincoln",
      admitted: "1867-03-01",
      region: "Midwest",
      population: 1961504,
      largestCity: "Omaha",
    },
    {
      name: "Nevada",
      abbreviation: "NV",
      capital: "Carson City",
      admitted: "1864-10-31",
      region: "West",
      population: 3104614,
      largestCity: "Las Vegas",
    },
    {
      name: "New Hampshire",
      abbreviation: "NH",
      capital: "Concord",
      admitted: "1788-06-21",
      region: "Northeast",
      population: 1377529,
      largestCity: "Manchester",
    },
    {
      name: "New Jersey",
      abbreviation: "NJ",
      capital: "Trenton",
      admitted: "1787-12-18",
      region: "Northeast",
      population: 9288994,
      largestCity: "Newark",
    },
    {
      name: "New Mexico",
      abbreviation: "NM",
      capital: "Santa Fe",
      admitted: "1912-01-06",
      region: "West",
      population: 2117522,
      largestCity: "Albuquerque",
    },
    {
      name: "New York",
      abbreviation: "NY",
      capital: "Albany",
      admitted: "1788-07-26",
      region: "Northeast",
      population: 20201249,
      largestCity: "New York City",
    },
    {
      name: "North Carolina",
      abbreviation: "NC",
      capital: "Raleigh",
      admitted: "1789-11-21",
      region: "South",
      population: 10439388,
      largestCity: "Charlotte",
    },
    {
      name: "North Dakota",
      abbreviation: "ND",
      capital: "Bismarck",
      admitted: "1889-11-02",
      region: "Midwest",
      population: 779094,
      largestCity: "Fargo",
    },
    {
      name: "Ohio",
      abbreviation: "OH",
      capital: "Columbus",
      admitted: "1803-03-01",
      region: "Midwest",
      population: 11799448,
      largestCity: "Columbus",
    },
    {
      name: "Oklahoma",
      abbreviation: "OK",
      capital: "Oklahoma City",
      admitted: "1907-11-16",
      region: "South",
      population: 3959353,
      largestCity: "Oklahoma City",
    },
    {
      name: "Oregon",
      abbreviation: "OR",
      capital: "Salem",
      admitted: "1859-02-14",
      region: "West",
      population: 4237256,
      largestCity: "Portland",
    },
    {
      name: "Pennsylvania",
      abbreviation: "PA",
      capital: "Harrisburg",
      admitted: "1787-12-12",
      region: "Northeast",
      population: 13002700,
      largestCity: "Philadelphia",
    },
    {
      name: "Rhode Island",
      abbreviation: "RI",
      capital: "Providence",
      admitted: "1790-05-29",
      region: "Northeast",
      population: 1097379,
      largestCity: "Providence",
    },
    {
      name: "South Carolina",
      abbreviation: "SC",
      capital: "Columbia",
      admitted: "1788-05-23",
      region: "South",
      population: 5118425,
      largestCity: "Charleston",
    },
    {
      name: "South Dakota",
      abbreviation: "SD",
      capital: "Pierre",
      admitted: "1889-11-02",
      region: "Midwest",
      population: 886667,
      largestCity: "Sioux Falls",
    },
    {
      name: "Tennessee",
      abbreviation: "TN",
      capital: "Nashville",
      admitted: "1796-06-01",
      region: "South",
      population: 6910840,
      largestCity: "Nashville",
    },
    {
      name: "Texas",
      abbreviation: "TX",
      capital: "Austin",
      admitted: "1845-12-29",
      region: "South",
      population: 29145505,
      largestCity: "Houston",
    },
    {
      name: "Utah",
      abbreviation: "UT",
      capital: "Salt Lake City",
      admitted: "1896-01-04",
      region: "West",
      population: 3271616,
      largestCity: "Salt Lake City",
    },
    {
      name: "Vermont",
      abbreviation: "VT",
      capital: "Montpelier",
      admitted: "1791-03-04",
      region: "Northeast",
      population: 643077,
      largestCity: "Burlington",
    },
    {
      name: "Virginia",
      abbreviation: "VA",
      capital: "Richmond",
      admitted: "1788-06-25",
      region: "South",
      population: 8631393,
      largestCity: "Virginia Beach",
    },
    {
      name: "Washington",
      abbreviation: "WA",
      capital: "Olympia",
      admitted: "1889-11-11",
      region: "West",
      population: 7705281,
      largestCity: "Seattle",
    },
    {
      name: "West Virginia",
      abbreviation: "WV",
      capital: "Charleston",
      admitted: "1863-06-20",
      region: "South",
      population: 1793716,
      largestCity: "Charleston",
    },
    {
      name: "Wisconsin",
      abbreviation: "WI",
      capital: "Madison",
      admitted: "1848-05-29",
      region: "Midwest",
      population: 5893718,
      largestCity: "Milwaukee",
    },
    {
      name: "Wyoming",
      abbreviation: "WY",
      capital: "Cheyenne",
      admitted: "1890-07-10",
      region: "West",
      population: 576851,
      largestCity: "Cheyenne",
    },
  ];
  
  export const STATE_NAMES = STATES.map((state) => state.name);