export const generateSampleUsers = () => [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        username: "jdoe",
        email: "john.doe@example.com",
        created: "2024-01-15",
        lastSignin: "2024-01-15 09:30",
        title: "Senior Analyst",
    },
    {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        username: "jsmith",
        email: "jane.smith@example.com",
        created: "2024-01-14",
        lastSignin: "2024-01-14 15:45",
        title: "Reviewer",
    },
    {
        id: 3,
        firstName: "Emily",
        lastName: "Johnson",
        username: "ejohnson",
        email: "emily.johnson@example.com",
        created: "2024-01-13",
        lastSignin: "2024-01-13 10:00",
        title: "Project Manager",
    },
    {
        id: 4,
        firstName: "Michael",
        lastName: "Brown",
        username: "mbrown",
        email: "michael.brown@example.com",
        created: "2024-01-12",
        lastSignin: "2024-01-12 14:20",
        title: "Software Engineer",
    },
    {
        id: 5,
        firstName: "Sarah",
        lastName: "Davis",
        username: "sdavis",
        email: "sarah.davis@example.com",
        created: "2024-01-11",
        lastSignin: "2024-01-11 16:10",
        title: "UI/UX Designer",
    },
    {
        id: 6,
        firstName: "Daniel",
        lastName: "Martinez",
        username: "dmartinez",
        email: "daniel.martinez@example.com",
        created: "2024-01-10",
        lastSignin: "2024-01-10 09:50",
        title: "Data Scientist",
    },
    {
        id: 7,
        firstName: "Jessica",
        lastName: "Garcia",
        username: "jgarcia",
        email: "jessica.garcia@example.com",
        created: "2024-01-09",
        lastSignin: "2024-01-09 13:30",
        title: "Marketing Specialist",
    },
    {
        id: 8,
        firstName: "Andrew",
        lastName: "Wilson",
        username: "awilson",
        email: "andrew.wilson@example.com",
        created: "2024-01-08",
        lastSignin: "2024-01-08 11:15",
        title: "Business Analyst",
    },
    {
        id: 9,
        firstName: "Sophia",
        lastName: "Moore",
        username: "smoore",
        email: "sophia.moore@example.com",
        created: "2024-01-07",
        lastSignin: "2024-01-07 08:45",
        title: "Quality Assurance",
    },
    {
        id: 10,
        firstName: "Ethan",
        lastName: "Taylor",
        username: "etaylor",
        email: "ethan.taylor@example.com",
        created: "2024-01-06",
        lastSignin: "2024-01-06 10:40",
        title: "DevOps Engineer",
    },
    {
        id: 11,
        firstName: "Liam",
        lastName: "Anderson",
        username: "landerson",
        email: "liam.anderson@example.com",
        created: "2024-01-05",
        lastSignin: "2024-01-05 09:00",
        title: "Product Manager",
    },
    {
        id: 12,
        firstName: "Olivia",
        lastName: "Thomas",
        username: "othomas",
        email: "olivia.thomas@example.com",
        created: "2024-01-04",
        lastSignin: "2024-01-04 15:20",
        title: "Content Strategist",
    },
    {
        id: 13,
        firstName: "Mason",
        lastName: "White",
        username: "mwhite",
        email: "mason.white@example.com",
        created: "2024-01-03",
        lastSignin: "2024-01-03 11:45",
        title: "Frontend Developer",
    },
    {
        id: 14,
        firstName: "Emma",
        lastName: "Harris",
        username: "eharris",
        email: "emma.harris@example.com",
        created: "2024-01-02",
        lastSignin: "2024-01-02 14:10",
        title: "Graphic Designer",
    },
    {
        id: 15,
        firstName: "Aiden",
        lastName: "Clark",
        username: "aclark",
        email: "aiden.clark@example.com",
        created: "2024-01-01",
        lastSignin: "2024-01-01 09:15",
        title: "Cloud Architect",
    },
    {
        id: 16,
        firstName: "Isabella",
        lastName: "Lewis",
        username: "ilewis",
        email: "isabella.lewis@example.com",
        created: "2023-12-31",
        lastSignin: "2023-12-31 12:40",
        title: "HR Manager",
    },
    {
        id: 17,
        firstName: "James",
        lastName: "Walker",
        username: "jwalker",
        email: "james.walker@example.com",
        created: "2023-12-30",
        lastSignin: "2023-12-30 10:50",
        title: "System Administrator",
    },
    {
        id: 18,
        firstName: "Charlotte",
        lastName: "Hall",
        username: "chall",
        email: "charlotte.hall@example.com",
        created: "2023-12-29",
        lastSignin: "2023-12-29 13:15",
        title: "Recruitment Specialist",
    },
    {
        id: 19,
        firstName: "Benjamin",
        lastName: "King",
        username: "bking",
        email: "benjamin.king@example.com",
        created: "2023-12-28",
        lastSignin: "2023-12-28 11:30",
        title: "Technical Writer",
    },
    {
        id: 20,
        firstName: "Amelia",
        lastName: "Scott",
        username: "ascott",
        email: "amelia.scott@example.com",
        created: "2023-12-27",
        lastSignin: "2023-12-27 08:25",
        title: "Accountant",
    },
    {
        id: 21,
        firstName: "Lucas",
        lastName: "Green",
        username: "lgreen",
        email: "lucas.green@example.com",
        created: "2023-12-26",
        lastSignin: "2023-12-26 15:00",
        title: "Network Engineer",
    },
    {
        id: 22,
        firstName: "Mila",
        lastName: "Adams",
        username: "madams",
        email: "mila.adams@example.com",
        created: "2023-12-25",
        lastSignin: "2023-12-25 09:35",
        title: "Social Media Manager",
    },
    {
        id: 23,
        firstName: "Alexander",
        lastName: "Mitchell",
        username: "amitchell",
        email: "alexander.mitchell@example.com",
        created: "2023-12-24",
        lastSignin: "2023-12-24 12:20",
        title: "IT Consultant",
    },
    {
        id: 24,
        firstName: "Harper",
        lastName: "Perez",
        username: "hperez",
        email: "harper.perez@example.com",
        created: "2023-12-23",
        lastSignin: "2023-12-23 10:00",
        title: "SEO Specialist",
    },
    {
        id: 25,
        firstName: "Elijah",
        lastName: "Roberts",
        username: "eroberts",
        email: "elijah.roberts@example.com",
        created: "2023-12-22",
        lastSignin: "2023-12-22 14:30",
        title: "Operations Manager",
    },
    {
        id: 26,
        firstName: "Avery",
        lastName: "Turner",
        username: "aturner",
        email: "avery.turner@example.com",
        created: "2023-12-21",
        lastSignin: "2023-12-21 11:50",
        title: "Backend Developer",
    },
];
