export const USER_ROLES = [
    "Admin",
    "System Administrators",
    "Development",
    "AAP User",
    "TSA Analyst",
    "FAA Analyst",
    "TSA Financial",
    "TSA Supervisor",
    "FAA Reviewer",
    "DASSP Report Viewer",
    "IAPWG - USSS",
    "IAPWG - FAA",
    "IAPWG - USCP",
    "IAPWG - EADS",
    "IAPWG - USPP",
    "Deployment",
    "TSA - UCU",
    "Extended Session",
    "IAPWG - TSA-UCU",
    "TSA Administrator",
    "Test Account",
    "FAA Req. Cert. Queue Viewer",
    "IAPWG - TSA",
    "NCRCC Watch Officers",
];